In [2]:
import pickle as pkl
import torch
import gym as gym
import numpy as np

In [27]:
# main/actor/0/dense/bias (DT_FLOAT) [512]
# main/actor/0/dense/kernel (DT_FLOAT) [84,512]
# main/actor/1/dense/bias (DT_FLOAT) [256]
# main/actor/1/dense/kernel (DT_FLOAT) [512,256]
# main/actor/logstd/bias (DT_FLOAT) [12]
# main/actor/mean/dense/bias (DT_FLOAT) [12]
# main/actor/mean/dense/kernel (DT_FLOAT) [256,12]

In [28]:
# print(f"w_0: {w_0.shape}")
# print(f"b_0: {b_0.shape}")
# print(f"w_1: {w_1.shape}")
# print(f"b_1: {b_1.shape}")
# print(f"w_mean: {w_mean.shape}")
# print(f"b_mean: {b_mean.shape}")
# print(f"b_std: {b_std.shape}")

w_0: torch.Size([512, 84])
b_0: torch.Size([512])
w_1: torch.Size([256, 512])
b_1: torch.Size([256])
w_mean: torch.Size([12, 256])
b_mean: torch.Size([12])
b_std: torch.Size([12])


In [3]:
# s_obs = "[[1.06596638e-02 -4.36880985e-02  1.50585829e-05  7.14926189e-03 1.06596638e-02 -4.36880985e-02  1.50585829e-05  7.14926189e-03 1.06596638e-02 -4.36880985e-02  1.50585829e-05  7.14926189e-03 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.92678475e-01  1.10223246e+00 -2.65736890e+00  2.50114709e-01 1.15086460e+00 -2.66086650e+00 -3.23189527e-01  1.12085938e+00 -2.67494226e+00  2.62883842e-01  1.12452579e+00 -2.68033648e+00 -2.92678475e-01  1.10223246e+00 -2.65736890e+00  2.50114709e-01 1.15086460e+00 -2.66086650e+00 -3.23189527e-01  1.12085938e+00 -2.67494226e+00  2.62883842e-01  1.12452579e+00 -2.68033648e+00 -2.92678475e-01  1.10223246e+00 -2.65736890e+00  2.50114709e-01 1.15086460e+00 -2.66086650e+00 -3.23189527e-01  1.12085938e+00 -2.67494226e+00  2.62883842e-01  1.12452579e+00 -2.68033648e+00]]"

# for _ in range (5):
#     s_obs = s_obs.replace("  ", " ")
# s_obs = s_obs.replace(" ", ",")
# with open("obsfile.txt", "w") as f:
#     f.write(s_obs)

obs = np.array([[1.06596638e-02,-4.36880985e-02,1.50585829e-05,7.14926189e-03,1.06596638e-02,-4.36880985e-02,1.50585829e-05,7.14926189e-03,1.06596638e-02,-4.36880985e-02,1.50585829e-05,7.14926189e-03,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,0.00000000e+00,-2.92678475e-01,1.10223246e+00,-2.65736890e+00,2.50114709e-01,1.15086460e+00,-2.66086650e+00,-3.23189527e-01,1.12085938e+00,-2.67494226e+00,2.62883842e-01,1.12452579e+00,-2.68033648e+00,-2.92678475e-01,1.10223246e+00,-2.65736890e+00,2.50114709e-01,1.15086460e+00,-2.66086650e+00,-3.23189527e-01,1.12085938e+00,-2.67494226e+00,2.62883842e-01,1.12452579e+00,-2.68033648e+00,-2.92678475e-01,1.10223246e+00,-2.65736890e+00,2.50114709e-01,1.15086460e+00,-2.66086650e+00,-3.23189527e-01,1.12085938e+00,-2.67494226e+00,2.62883842e-01,1.12452579e+00,-2.68033648e+00]])

In [4]:
target_act = np.array([-0.59512997, -1.7298914, 0.03665851, -0.70346016, -1.8998375, -0.79841995, -0.09894164, 2.6849961, -0.59932446, -0.4341147, -1.7428617, 0.5702265 ])

In [5]:
pi = np.pi
two_pi = 2 * pi
two_thousand_pi = 1000 * two_pi

high = np.array(([two_pi, ] * 2 + [two_thousand_pi, ] * 2) * 3 + [1.0, ] * 36 + [pi, ] * 36)
low = -high

act_high = np.array([3.2114058, 13.155161, 3.5348086, 3.2114058, 13.155161, 3.5348086, 3.2114058, 13.155161, 3.5348086, 3.2114058, 13.155161, 3.5348086])
act_low = -act_high

In [24]:
class ResetModel(torch.nn.Module):

    def __init__(self):
        super().__init__()

        with open("weights.pkl", "rb") as f:
            weights = pkl.load(f)

        w_0 = torch.Tensor(weights["main/actor/0/dense/kernel"]).T
        b_0 = torch.Tensor(weights["main/actor/0/dense/bias"])
        w_1 = torch.Tensor(weights["main/actor/1/dense/kernel"]).T
        b_1 = torch.Tensor(weights["main/actor/1/dense/bias"])
        w_mean = torch.Tensor(weights["main/actor/mean/dense/kernel"]).T
        b_mean = torch.Tensor(weights["main/actor/mean/dense/bias"])
        b_std = torch.Tensor(weights["main/actor/logstd/bias"])

        # observation_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(84, ))
        # high = observation_space.high
        # low = observation_space.low

        self.obs_mean = torch.Tensor(weights["resource/s_norm/mean"])
        self.obs_std = torch.Tensor(weights["resource/s_norm/std"])
        self.obs_mean.requires_grad = False
        self.obs_std.requires_grad = False

        self.act_mean = torch.Tensor(weights["resource/a_norm/mean"])
        self.act_std = torch.Tensor(weights["resource/a_norm/std"])
        self.act_mean.requires_grad = False
        self.act_std.requires_grad = False

        self.fc0 = torch.nn.Linear(in_features=84, out_features=512, bias=True)
        self.fc1 = torch.nn.Linear(in_features=512, out_features=256, bias=True)
        self.mu = torch.nn.Linear(in_features=256, out_features=12, bias=True)

        # fill weights

        self.fc0.weight = torch.nn.Parameter(w_0)
        self.fc0.bias = torch.nn.Parameter(b_0)
        self.fc1.weight = torch.nn.Parameter(w_1)
        self.fc1.bias = torch.nn.Parameter(b_1)
        self.mu.weight = torch.nn.Parameter(w_mean)
        self.mu.bias = torch.nn.Parameter(b_mean)

    def forward(self, x):
        # normalize x
        x = (x - self.obs_mean) / self.obs_std
        # inference
        x = torch.nn.functional.relu(self.fc0(x))
        x = torch.nn.functional.relu(self.fc1(x))
        x = self.mu(x)
        x = torch.tanh(x)
        # unnormalize output:
        x = x * self.act_std + self.act_mean

        return x

In [25]:
model = ResetModel()

In [26]:
with torch.no_grad():
    result = model(torch.Tensor(obs))
print(f"result:\n{result}\n\nexpected:\n{torch.Tensor(target_act)}")

result:
tensor([[-0.5951, -1.7299,  0.0367, -0.7035, -1.8998, -0.7984, -0.0989,  2.6850,
         -0.5993, -0.4341, -1.7429,  0.5702]])

expected:
tensor([-0.5951, -1.7299,  0.0367, -0.7035, -1.8998, -0.7984, -0.0989,  2.6850,
        -0.5993, -0.4341, -1.7429,  0.5702])


In [17]:
with open("weights.pkl", "rb") as f:
    weights = pkl.load(f)

weights["resource/s_norm/mean_ph"]

array([ 0.15355109,  0.10605378, -0.09990677,  0.07711993, -0.0755351 ,
       -0.11750013, -0.04986651, -0.01949827, -0.03155179,  0.0861546 ,
        0.11604203,  0.05634367, -0.0157914 , -0.07788604,  0.12080891,
        0.01823236,  0.17470159, -0.12190854,  0.1261829 ,  0.05097049,
       -0.06850047, -0.05139183, -0.11558472, -0.10547166, -0.1365947 ,
       -0.02511717, -0.04450043, -0.176195  ,  0.09925593,  0.07895605,
       -0.16166645, -0.09049367, -0.02240962,  0.04504484, -0.17767791,
       -0.10477796, -0.03373881,  0.1141827 ,  0.14354096, -0.14140195,
       -0.02814433, -0.00841437, -0.04031008, -0.13807724,  0.18135388,
       -0.16665038,  0.08624165,  0.01969892,  0.02126883,  0.13084783,
        0.02046132,  0.11859854, -0.14120725, -0.1550895 ,  0.07388838,
       -0.1677464 , -0.023197  , -0.18706934,  0.02256899,  0.00770594,
       -0.17406484,  0.1047257 ,  0.06806169,  0.02282919,  0.01606287,
        0.1072592 ,  0.00050364,  0.08467285, -0.10496008, -0.09